### ISSUE TITLE
Can the current method ranking be displayed on Github

### ISSUE THREAD

**Issue by isCopyman** [qile2000/LAMDA-TALENT#10]
Is it possible to update the average rank of existing methods on different tasks in the Github repository or somewhere else

**Comment by 6sy666** [comment]
We have evaluated some methods, such as mlp_plr and excel_former, and we are currently organizing the results. Once finalized, they will be updated at the following link:
🔗 https://github.com/qile2000/LAMDA-TALENT/tree/main/example_datasets

However, for other methods like BiShop and Trompt, the computational cost is quite high, and unfortunately, we don't currently have sufficient resources to evaluate them. We will keep this in mind for future updates if resources become available.
