### ISSUE TITLE
Some questions about the table 3 in the paper "A Closer Look at Deep Learning on Tabular Data"

### ISSUE THREAD

**Issue by isCopyman** [qile2000/LAMDA-TALENT#2]
What are the meanings of the values in Table 3 of the paper "A Closer Look at Deep Learning on Tabular Data"? It seems that there is no explanation for this in the paper.

**Comment by isCopyman** [comment]
![image](https://github.com/user-attachments/assets/af5e1eec-2339-4229-b6f2-06a72ed95dc5)

**Comment by 6sy666** [comment]
Thank you for pointing this out! The values in Table 3 of the paper "A Closer Look at Deep Learning on Tabular Data" represent the **average rank**, with smaller values indicating better performance. Although this is mentioned in **Appendix C.2**, we appreciate your feedback highlighting the lack of clarity at this point in the main text. We'll work on improving this aspect in future revisions.

**Comment by isCopyman** [comment]
> > What are the meanings of the values in Table 3 of the paper "A Closer Look at Deep Learning on Tabular Data"? It seems that there is no explanation for this in the paper.
> 
> Thank you for pointing this out! The values in Table 3 of the paper "A Closer Look at Deep Learning on Tabular Data" represent the **average rank**, with smaller values indicating better performance. Although this is mentioned in **Appendix C.2**, we appreciate your feedback highlighting the lack of clarity at this point in the main text. We'll work on improving this aspect in future revisions.

May I ask how the **average rank** is calculated, which is not mentioned in Appendix C-2. Does it refer to the **average rank** of three different encoding strategies (Vanilla, E-Q, E-T) for a certain method, such as MLP, in a certain type of dataset, such as TF?

**Comment by 6sy666** [comment]
> May I ask how the **average rank** is calculated, which is not mentioned in Appendix C-2. Does it refer to the **average rank** of three different encoding strategies (Vanilla, E-Q, E-T) for a certain method, such as MLP, in a certain type of dataset, such as TF?

Yes, you are correct.
