### ISSUE TITLE
 The Distance Measurement in the paper of Modern NCA

### ISSUE THREAD

**Issue by isCopyman** [qile2000/LAMDA-TALENT#4]
![image](https://github.com/user-attachments/assets/44eeeb42-489a-4f75-be65-db073516c33b)
The cosine distance and inner product distance in the figure do not seem to use mapping $$\phi$$, is this a typographical error or is it intentionally designed in this way?

**Comment by 6sy666** [comment]
Thank you for pointing that out! This is a typographical error, and the mapping 𝜙 should indeed be used. We will correct this in the next version. Thanks again for your attention to detail!
